# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - laravel_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  laravel:
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: always
    # user: 1000:1000
    ports: 
      - 8000:8000
    volumes:
      - .:/var/www/html
    command: php artisan key:generate
    #command: php artisan serve --host 0.0.0.0

volumes:
  laravel_db: